### ISSUE TITLE
Search Filters / Options

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-android#108]
Similar to odysee.com searc page

**Comment by kekkyojin** [comment]
This seems fixed to me. It could be reopened or create a new one for filters not yet implemented

**Comment by tzarebczan** [comment]
- [ ] add relevancy vs oldest/newest sort option 
- [ ] Add resolving of channels/claim to top result - i.e. type "rekieta" or "rekietalaw" on odysee vs app. Needs to resolve all channels/claims, and show highest bid. Also remove spaces and replace with - when resolving

**Comment by tzarebczan** [comment]
@ktprograms those couple bugs/enhancements also worth looking into.
