### ISSUE TITLE
[Feature Request] Show, change or remove your profile picture

### ISSUE THREAD

**Issue by nphalem** [OdyseeTeam/odysee-android#112]
Show the profile icon in top-right corner while on screens Home, Following, Wallet, Library and Channels _(when you click on your icon and go to Channels)_.

Add option to **change** or **remove** your profile picture.

**Comment by tzarebczan** [comment]
If you go to Account > channels > click your channel > Edit, you can update this. At this time we don't support removing.

**Comment by tzarebczan** [comment]
Or long press the channel > edit

**Comment by nphalem** [comment]
Thanks for the instructions. Just a note that that profile icon is still not showing when on Home screen or any other tab.

Am I only one having that issue? Should I open an new issue for this?

**Comment by kekkyojin** [comment]
Odysee Android is not showing currently logged in user profile image yet, @nphalem
