### ISSUE TITLE
[Bug] Issue after going to back to video from PiP mode. 

### ISSUE THREAD

**Issue by nphalem** [OdyseeTeam/odysee-android#115]
### Steps to reproduce
1. Play video
2. Press home button to enter PiP mode
3. Try to open Odysee from PiP mode to get back to the video

### Expected behavior
After pressing the _enlarge_ button in PiP mode application should open the video page.

### Actual behavior
After pressing the _enlarge_ button in PiP mode application opens Home page.

## System Configuration
- Device: Oneplus 5T (A5010)
- Android version: LineageOS 18.1 (Android 11)

## Anything Else
After coming back to the application on Home screen player isn't even minimized.
To get back to the video you need to switch to other tab (Following/Wallet/Library) and then player will be shown minimized.

## Screen recording
<img src="https://i.imgur.com/WgFyfEa.gif"/>

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for the issues. This one is covered in https://github.com/OdyseeTeam/odysee-android/issues/91
