### ISSUE TITLE
video clicked in related content does not play

### ISSUE THREAD

**Issue by nhnifong** [OdyseeTeam/odysee-android#131]
## The Issue
When clicking a video from the related content below a playing video, the clicked video does not play. Instead the currently playing video briefly pauses and then resumes where it left off, and the related content view is scrolled to its top.

### Steps to reproduce
1. Play a video in portrait mode
2. Click any video in the related content view below it
3.

## System Configuration
- Device: pixel 4a 5G
- Android version: R

I built Odyssey for Android from source, at a commit from February 18th, commenting out dependencies on GMS core and firebase.

## Screenshots
![Screenshot_20220219-073704](https://user-images.githubusercontent.com/345920/154801227-8599f445-9994-4957-ae1c-53ccd1ddbbba.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
