### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-android#148]
Ability to cast videos to chromecast devices

**Comment by mpact1984** [comment]
Hi,
i would apprecisate this too. The cast button is already implemented, but results in a black screen only. I hope we can enjoy this very soon.

**Comment by kekkyojin** [comment]
odysee-android -this repository- does not yet support Chromecast. Some parts are implemented -as they were on LBRY Android-, but not wired at all.

Maybe @mpact1984 is having the problem with the non-native one?

**Comment by mpact1984** [comment]
@kekkyojin Please explain to me what you mean with "the non-native one". The app? I use the Odysee app version from the google play store. Or did you mean the browser, because i switched to a different default browser? Or something complete different.

**Comment by kekkyojin** [comment]
The version on the Play Store is the non-native one, which is a different repository than this one. The non-native Odysee Android loads web assets which had been packaged.

**Comment by kekkyojin** [comment]
Unable to work on this for a time. Unassigning from me.

**Comment by tzarebczan** [comment]
@ktprograms do you have a chromecast? If not, Odysee can reimburse you for one. This would be a good one to work on while I spec out publishing flow.
