### ISSUE TITLE
F-Droid!

### ISSUE THREAD

**Issue by EricDriussi** [OdyseeTeam/odysee-android#170]
## The Issue
Odysee is not on F-Droid

### Steps to reproduce
1. Go to F-Droid
2. App isn't there
3. sad

Jokes aside, I'm going to try and get Odysee on F-Droid.

It will be the first time I do something like this so it might take a while :)

Just thought I'd post this for reference and to leave future updates.

Cheers!

**Comment by kekkyojin** [comment]
Duplicates #139
