### ISSUE TITLE
Issue when playing certain videos

### ISSUE THREAD

**Issue by kossy18** [OdyseeTeam/odysee-android#177]
### Steps to reproduce
1. Play a video. I was able to reproduce the issue while playing the following videos:
https://odysee.com/@Odysee:8/Julian:9
https://odysee.com/@Odysee:8/Odysee-Android-App:1

### Expected behaviour
The video should continue playing until it's finished or is interrupted

### Actual behaviour
The application closes but the audio can still be heard in the background

## System Configuration
- Device: Samsung Galaxy Note 10+
- Android version: Android 11

## Screenshots

![Issue](https://user-images.githubusercontent.com/11820472/163674355-d51aa52e-625f-4df9-92b7-2b3c04d0904c.gif)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thank you for the report!

**Comment by kossy18** [comment]
> Thank you for the report!

You're welcome.

**Comment by kossy18** [comment]
I suppose I can close this issue as it has been fixed and merged in this pull request https://github.com/OdyseeTeam/odysee-android/pull/178
