### ISSUE TITLE
Other language homepage support

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-android#195]
Similar to odysee.com, have option to change the homepage language.

**Comment by kekkyojin** [comment]
Is this about the language of the content being shown? In that case this is one of my favourite new additions

**Comment by tzarebczan** [comment]
- [ ] get up to speed with v2 - including not claim ids for wild west
- [ ] Make sure it's working
https://github.com/OdyseeTeam/odysee-android/blob/master/app/src/main/java/com/odysee/app/utils/ContentSources.java

https://github.com/OdyseeTeam/odysee-android/blob/master/app/src/main/java/com/odysee/app/utils/ContentSources.java#L210-L246
