### ISSUE TITLE
Choice between Odysee and LBRY app shown when clicking media playing notification

### ISSUE THREAD

**Issue by ktprograms** [OdyseeTeam/odysee-android#210]
### Steps to reproduce
1. Start playing a video
2. Open the notifications shade
3. Tap on the media notification

### Expected behaviour

Opens currently playing media in Odysee.

### Actual behaviour

Shows "Open with" popup picking between LBRY and Odysee app.

## System Configuration
- Device: Samsung Galaxy A23
- Android version: 12

Reported by my friend

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kekkyojin** [comment]
This was a great catch, as user would expect the same app which created the notification would be opened without OS having to ask for it
