### ISSUE TITLE
Adding Videos to Watch Later

### ISSUE THREAD

**Issue by swriel21** [OdyseeTeam/odysee-android#215]
### Steps to reproduce
1. Go to Home or Following
2. Select "three dot" menu to see option to add to playlist.
3. Video is selected instead 50% of the time even when I am careful.

### Expected behaviour
Tell us what should happen
I should be able to add to Watch Later without starting the video every time.

### Actual behaviour
Tell us what happens instead
50% of the time, I have to take extra steps to wait for the video to load, then stop the video, and then add to Watch Later. 

## System Configuration
- Device: Pixel 5
- Android version: Most recent

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Closing this issue for now - this repo for the native app which isn't out yet. Sorry about the sub par performance on the currently released app, that was just a stop gap.
