### ISSUE TITLE
Run unit-tests on Github Actions

### ISSUE THREAD

**Issue by kekkyojin** [OdyseeTeam/odysee-android#284]
### Steps to reproduce
1. Developer may inadvertently change some code which makes tests no longer pass
2. Repository will still compile without errors
3. Something may be wrong at some time as there is some test which will fail

### Expected behaviour
After creating a PR, contributor and reviewers must be aware that some tests are no longer passing
### Actual behaviour
Nobody will be aware of tests no longer passing and bugs could appear

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by ktprograms** [comment]
Fixed by #289
