### ISSUE TITLE
Crashes on some videos

### ISSUE THREAD

**Issue by czarkoff** [OdyseeTeam/odysee-android#303]
## The Issue

The app crashes on some videos. Crashes seem to happen at some particular moments within the video.  When downloaded via web app and played locally with exoplayer-based video player, the videos that cause the crashes in this app play normally.  The crashes seem to happen after a fixed period of video beeing open, regardless of the position in the video.

### Steps to reproduce
1. Try playing [this video](https://odysee.com/@Huggbees:1/everybody-hates-the-french:2?r=H1MGWCETuaWRFUpwGg95wE8JDRnoWw5R).

### Expected behaviour
The video plays uninterrupted.

### Actual behaviour
The app crashes in approximately 5 seconds of playback.

## System Configuration
- Device: Xiaomi Redmi Note 8 Pro
- Android version: 12 (CrDroid 8.4)

## Anything Else
Seems to happen with particular videos only. That is, after reinstalling the app the same video consistently crashes while most videos are fine.

Captured trace: https://paste.crdroid.net/XxEPJA

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kekkyojin** [comment]
Thanks for the logcat, @czarkoff
