### ISSUE TITLE
Primary email address is not set when signing up

### ISSUE THREAD

**Issue by kekkyojin** [OdyseeTeam/odysee-android#372]
### Steps to reproduce
1. Create a new account
2. On Odysee.com, try to login, but click on the link for the "forgot password" case
3. After receiving the email from Odysee, try to set the new password

### Expected behaviour
The new password is set
### Actual behaviour
Odysee.com tells user that primary_email is needed

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Create and verify a new user on the Android app, or just cr create and not sign in?

**Comment by kekkyojin** [comment]
Create and verify the email. At least that was my case, @tzarebczan 

I created an account for developing the setting of a default channel after the first one is created, but today I forgot the password so the issue appeared.

**Comment by akinwale** [comment]
@kekkyojin Could you please test the latest build to confirm if this is still happening? There was a bug where the UI was being updated outside of the main thread (related to the sign in email address) which I fixed.

**Comment by kekkyojin** [comment]
I have just been able to change my password correctly on a scratch new account, @akinwale 

Just to clarify the steps for the bug to appear, which is no longer the case:

1. Create a new account on Odysee Android app
2. Verify the email address
3. Wait for Odysee Android to update the Home section with content and check you are now logged in with the new account
4. Go to odysee.com
5. Try to log in
6. When the password is requested, use link for forgotten password
