### ISSUE TITLE
app unusable on Android TV 

### ISSUE THREAD

**Issue by antoniotari** [OdyseeTeam/odysee-android#426]
## The Issue
The android tv app, downloaded from FDroid to a Shield Pro is unusable, navigation is buggy and slow and opens randomly drop down menus just by navigating with directional remote buttons

### Steps to reproduce
1. download the app from F-Droid to your Android TV device (I used an android tv pro)
2. login (or not) and try to use to app

### Expected behaviour
navigation with the directional buttons on the tv remote should move around the app and the videos like any other tv app (youtube, netflix, prime videos, etc)

### Actual behaviour
navigation is buggy and slow and opens randomly drop down menus

## System Configuration
- Device: NVIDIA shield pro
- Android version: 11

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
There's no native android tv app at this time, support is planned for the future.
