### ISSUE TITLE
Language list

### ISSUE THREAD

**Issue by beatnickgr** [OdyseeTeam/odysee-android#442]
Go to :
Edit upload
Language
Open the drop down list

Ελληνικά (Greek) is missing.

Please add it to the list.

Version 0.0.69 (latest on F-Droid)

**Comment by tzarebczan** [comment]
This repo is for the native app, not the web app in the wild. 

To add languages, typically we need to have translations for the site. You can help us at: https://explore.transifex.com/lbry/lbry-desktop/

**Comment by beatnickgr** [comment]
Thanks for the answer, I'm talking about the android app.
I see "Slovencina" in the list although it's only translated at 4% according to your link.
Greek is translated 13% but unlisted.
Why is that?
