### ISSUE TITLE
Dead Android App

### ISSUE THREAD

**Issue by Heus-Sueh** [OdyseeTeam/odysee-android#443]
the last app update was in November 2022, and so far there has been no news of the native app that was under development, at this point the native app for android should already be ready but apparently it is not and this web app that is available in the playstore is horrible for low end devices, what transpires to the community is that you do not care about android. Come on guys where is the transparency you are so proud of?

**Comment by tzarebczan** [comment]
Thanks for your feedback, don't have an ETA at this time nor did we ever promise one.

**Comment by Heus-Sueh** [comment]
sorry for the rather angry text, i agree that you guys never gave a date or promised anything but i still believe that the points mentioned are valid and that the lack of a proper native app is a bit disappointing apart from that i wish you guys success 👍
