### ISSUE TITLE
[Feature Request] - Swipe up/down to increase/decrease brightness and volume in fullscreen mode

### ISSUE THREAD

**Issue by clrizzi** [OdyseeTeam/odysee-android#455]
As described in the title, it would be interesting if there was an option to swipe up and down to increase/decrease volume and brightness when in full screen mode,

**Comment by kekkyojin** [comment]
Those features are managed by the operating system.

In the case of volume, it can be changed by physical volume buttons on the device. Brightness can be changed from notification shade. There is no need to replicate it at the application level.

Anyway, if someone starts to work on this, better to check if Google would reject an update containing this feature. I don't know if that would be the case. Just in case.
