### ISSUE TITLE
Cannot find channel or create a new one via app (is visible in browser)

### ISSUE THREAD

**Issue by devbrones** [OdyseeTeam/odysee-android#63]
### Steps to reproduce
1. download odysee-push.apk from build.lbry.io/android/
2. install apk on android 11
3. try to find account channel and / or create a new channel

### Expected behaviour
Tell us what should happen

I should see my channel and be able to create another one if it is not available

### Actual behaviour
Tell us what happens instead

Nothing, the app becomes unresponsive when i try to add a channel

## System Configuration
- Device: Fairphone 3
- Android version: Lineageos 18.1 (Android 11)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kekkyojin** [comment]
This is being worked on right now. A new PR will be created in coming days which will re-enable channel manager and also request user to create a channel when one is required.

Code for FileViewFragment is done now, it needs to be refactored so other parts of the app re-uses it.

I will be mentioning this bug and also alpha meta-bug when PR is created for your convenience

**Comment by devbrones** [comment]
@kekkyojin That is delightful to hear! Great work on the app so far! :]

_Sent from my FP3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by akinwale** [comment]
Fixed in https://github.com/OdyseeTeam/odysee-android/pull/65.
