### ISSUE TITLE
Publishing - match odysee.com file upload flow

### ISSUE THREAD

**Issue by akinwale** [OdyseeTeam/odysee-android#93]
Allow users to publish content from their devices.

**Comment by tzarebczan** [comment]
Probably the easiest way to spec this out would be to refer to the Odysee.com code for publishing, mainly for both livestream and file publishing. No need to support text at this time, but keep it in mind in case it's easy to add. 

- [ ] match hidden sections and defaults in a similar way
- [ ] support claim updates by passing the claim id as a param (the backend then assumes it's an update)
- [ ] support passing remote URL for publishing replays
- [ ] listing replays flow
- [ ] creating livestream claims, including anytime + future. 
- [ ] supporting editing properly (i.e. pass release time as the original post)
- [ ] support changing release time for past dates (future not allowed)

**Comment by ktprograms** [comment]
Should the Randomize button be kept in the URL field?

Currently, there's a field to change the channel to publish as, whereas on odysee.com there isn't (but the URL field shows which channel is being used). Should it be kept or removed?

**Comment by tzarebczan** [comment]
Don't need the randomize - auto suggest the url from the file selected, while filtering out non allowed characters. 

Odysee moved the selector to the bottom of the page for channels. 

Below the description is fine for thumbs. Would be awesome to have a way to pick from the video too similar to Odysee, but don't go crazy about it.

**Comment by ktprograms** [comment]
> auto suggest the url from the file selected, while filtering out non allowed characters.

Similar to the matching claim logic in search, right?
