### ISSUE TITLE
Direct livestreaming

### ISSUE THREAD

**Issue by akinwale** [OdyseeTeam/odysee-android#94]
Allow users to livestream directly from their devices.

**Comment by tzarebczan** [comment]
There are two parts of this process: 

1) creating a placeholder claim with no source data that includes all metadata for the stream (title, tags, thumbnail, etc). This process can be seen on Odysee.com in the upload button or page (requires approval on account or 50 LBC channel stake, or odysee Premium - coming soon). Streams can be one of two types: anytime, or scheduled. 

2) using your phone, capturing the video and audio and sending it to the RTMP server specified along with a stream key. 

For API details on 1, see network tab calls on odysee.com Livestream process. This includes getting a stream key, the rtmp server, and the publish process. Code at: https://github.com/OdyseeTeam/odysee-frontend

For 2, this will need to tap into the Android apis to create a video stream. Probably should have some type of bitrate control, with a reasonable default (3mbps).
